# Generated by Django 3.2.4 on 2021-06-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mog_status',
            field=models.BooleanField(default=False),
        ),
    ]
