# Generated by Django 3.2.4 on 2021-06-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mog',
            name='photo',
            field=models.ImageField(upload_to='static/img/mog'),
        ),
    ]
