# Generated by Django 3.2.4 on 2021-06-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mog', '0002_alter_mog_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mog',
            name='name_of_church',
            field=models.CharField(default='To be determined', max_length=100),
            preserve_default=False,
        ),
    ]
